from enum import Enum

class TopState(str, Enum):
    INIT = "INIT"
    READY = "READY"
    RUNNING = "RUNNING"
    AWAITING_AGENT_EVENT = "AWAITING_AGENT_EVENT"
    GATING = "GATING"
    VERIFYING = "VERIFYING"
    PAUSED_FOR_HUMAN = "PAUSED_FOR_HUMAN"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    ABORTED = "ABORTED"

class NodeStatus(str, Enum):
    CURRENT_STEP_PENDING = "CURRENT_STEP_PENDING"
    CURRENT_STEP_RUNNING = "CURRENT_STEP_RUNNING"
    CURRENT_STEP_BLOCKED = "CURRENT_STEP_BLOCKED"
    CURRENT_STEP_DONE = "CURRENT_STEP_DONE"
    BRANCH_DECISION_PENDING = "BRANCH_DECISION_PENDING"
    RETRY_PENDING = "RETRY_PENDING"
    ROLLUP_VERIFY_PENDING = "ROLLUP_VERIFY_PENDING"

class DecisionType(str, Enum):
    CONTINUE = "CONTINUE"
    RETRY = "RETRY"
    VERIFY_STEP = "VERIFY_STEP"
    ADVANCE_STEP = "ADVANCE_STEP"
    BRANCH = "BRANCH"
    ESCALATE_TO_HUMAN = "ESCALATE_TO_HUMAN"
    FINISH = "FINISH"
    ABORT = "ABORT"
