from enum import Enum

class TopState(str, Enum):
    READY = "READY"
    RUNNING = "RUNNING"
    GATING = "GATING"
    VERIFYING = "VERIFYING"
    PAUSED_FOR_HUMAN = "PAUSED_FOR_HUMAN"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    ABORTED = "ABORTED"

class DecisionType(str, Enum):
    CONTINUE = "CONTINUE"
    RETRY = "RETRY"
    VERIFY_STEP = "VERIFY_STEP"
    ADVANCE_STEP = "ADVANCE_STEP"
    BRANCH = "BRANCH"
    ESCALATE_TO_HUMAN = "ESCALATE_TO_HUMAN"
    FINISH = "FINISH"
    ABORT = "ABORT"
